mport cron from "node-cron";
import moment from "moment-timezone";
import { autoGenerateWinningNumbers } from "../controller/autoDraw.controller.js";

// -----------------------------
// PREVENT MULTIPLE PM2 INSTANCES
// -----------------------------
const instance = process.env.NODE_APP_INSTANCE;
// Scheduler should run ONLY on instance 0
const shouldRunScheduler = !instance || instance === "0";

function startScheduler() {
  // Runs every minute
  cron.schedule("* * * * *", async () => {
    try {
      const now = moment().tz("Asia/Kolkata");
      const hour = now.hour();
      const minute = now.minute();

      // Draw window 9 AM – 11 PM
      if (hour < 9 || hour > 23) return;

      // Allowed draw times: 00, 15, 30, 45
      if (![0, 15, 30, 45].includes(minute)) return;

      const drawTime = now.format("hh:mm A");

      console.log(`⏳ Auto draw triggered for ${drawTime}`);

      // Only ONE result generated by this instance
      await autoGenerateWinningNumbers(drawTime);

      console.log(`✅ Global Draw saved for: ${drawTime}`);

    } catch (err) {
      console.error("❌ Auto Draw Scheduler Error:", err);
    }
  });

  console.log("🎯 Auto Draw Scheduler Started (Instance 0)...");
}

if (shouldRunScheduler) {
  startScheduler();
} else {
  console.log("⛔ Scheduler disabled for PM2 instance:", instance);
}